export const GET_ORDERS_RESET = "GET_ORDERS_RESET";
export const GET_ORDERS_LOADING = "GET_ORDERS_LOADING";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_FAILURE = "GET_ORDERS_FAILURE";

export const GET_ORDER_LOADING = "GET_ORDER_LOADING";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAILURE = "GET_ORDER_FAILURE";

export const CREATE_ORDER_LOADING = "CREATE_ORDER_LOADING";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE";
export const DELETE_ORDER = "DELETE_ORDER";
export const DELETE_ORDER_FAILURE = "DELETE_ORDER_FAILURE";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const ORDER_STATUS_CHANGED = "ORDER_STATUS_CHANGED";

export const ADD_MEDICINES_TO_PENDING_CART = "ADD_MEDICINES_TO_PENDING_CART";
export const ADD_MEDICINES_TO_USER_CART_SUCCESS =
  "ADD_MEDICINES_TO_USER_CART_SUCCESS";
export const ORDER_FAILURE = "ORDER_FAILURE";
export const ORDER_LOADING = "ORDER_LOADING";
export const INCRESE_QUANTITY = "INCRESE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
export const SEND_COMMENT = "SEND_COMMENT";
