export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";
export const GET_PRODUCTS_LOADING = "GET_PRODUCTS_LOADING";

export const GET_MAIN_PRODUCTS_SUCCESS = "GET_MAIN_PRODUCTS_SUCCESS";
export const GET_MAIN_PRODUCTS_FAILURE = "GET_MAIN_PRODUCTS_FAILURE";
export const GET_MAIN_PRODUCTS_LOADING = "GET_MAIN_PRODUCTS_LOADING";

export const RESET_PRODUCTS = "RESET_PRODUCTS";

export const SET_PRODUCT_SUCCESS = "SET_PRODUCT_SUCCESS";
export const SET_PRODUCT_LOADING = "SET_PRODUCT_LOADING";
export const SET_PRODUCT_FAILURE = "SET_PRODUCT_FAILURE";

export const SET_PRODUCT_FORM_SUCCESS = "SET_PRODUCT_FORM_SUCCESS";
export const SET_PRODUCT_FORM_LOADING = "SET_PRODUCT_FORM_LOADING";
export const SET_PRODUCT_FORM_FAILURE = "SET_PRODUCT_FORM_FAILURE";
